-- MySQL Script generated by MySQL Workbench
-- Wed Feb 17 09:39:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Library_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Library_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Library_DB` DEFAULT CHARACTER SET utf8 ;
USE `Library_DB` ;

-- -----------------------------------------------------
-- Table `Library_DB`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_DB`.`Books` (
  `bID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bName` VARCHAR(64) NOT NULL DEFAULT 'MysteryBook',
  `bAuthor` VARCHAR(64) NULL DEFAULT 'MysteryAuthor',
  `bAmount` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`bID`),
  UNIQUE INDEX `idBooks_UNIQUE` (`bID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_DB`.`Readers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_DB`.`Readers` (
  `rID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rName` VARCHAR(64) NOT NULL DEFAULT 'MysteryReader',
  `rDate` DATE NOT NULL DEFAULT '2021-02-16',
  `bID` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`rID`),
  UNIQUE INDEX `idReaders_UNIQUE` (`rID` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
