/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Canvas;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.JPanel;
import java.awt.Color;
/**
 *
 * @author Pavel Zhukosvkiy
 */
public class MainFrame extends javax.swing.JFrame {

    private static final int RECT3D_WIDTH = 130, RECT3D_HEIGHT = 70,
                             RECT3D_X = 100, RECT3D_Y = 100, DEPTH = 5;

    private static final boolean RAISED_or_NOT = true;
    
    /**
     * Creates new form EllipseGradientFrame
     */
    public MainFrame() {
        super("Lab 8, Var 5, 3D Rectangular");
        initComponents();
        myInitComponents();
    }

    
    private void myInitComponents(){
        RectangleCanvas3D ellipseGradient = 
                new RectangleCanvas3D(RECT3D_WIDTH, RECT3D_HEIGHT, DEPTH); // Добавить 3 свойство (глубину)
        ellipseGradient.setUpCoordinates(RECT3D_X, RECT3D_Y);
        ellipseGradient.setUpRaised(RAISED_or_NOT);
        
        DrawingPanel dpanel = new DrawingPanel();
        dpanel.setCanvasToDraw(ellipseGradient);
        
        this.setContentPane(dpanel);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lab 8, Var 5, 3D Rectangular");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

}


class DrawingPanel extends JPanel {
    
    private Canvas canvasToDraw;
    
    DrawingPanel(){
        setPreferredSize(new Dimension(420, 420));
    }
    
    public void setCanvasToDraw(Canvas canvas){
        this.canvasToDraw = canvas;
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        this.canvasToDraw.paint(g);
    }
}